# Generated by Django 4.2.16 on 2024-10-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='validacao',
            field=models.BooleanField(default=False),
        ),
    ]
