# Generated by Django 5.1.1 on 2024-10-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_denuncia_validacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cidade',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
