# Generated by Django 5.1.1 on 2024-10-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0005_remove_comentario_user_id_comentario_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comentario',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
