# Generated by Django 5.1.1 on 2024-11-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0007_artigo_created_at_artigo_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default='São Paulo', max_length=255),
        ),
    ]
