# Generated by Django 5.1.1 on 2024-11-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0008_endereco_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='title',
        ),
    ]
