# Generated by Django 5.1.1 on 2024-11-16 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0010_siteinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
