# Generated by Django 5.1.1 on 2024-10-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_remove_artigo_user_remove_comentario_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comentario',
            name='user_name',
            field=models.CharField(default='Tadaki', max_length=255),
        ),
    ]
