# Generated by Django 5.1.1 on 2024-10-28 03:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_remove_comentario_user_name_comentario_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='artigo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
